### ISSUE TITLE
Kinect v2 Not Detecting

### ISSUE THREAD

**Issue by lthursdayl** [OpenPTrack/open_ptrack#39] opened 2015-04-09 18:04 UTC
We have noticed that some of the time after starting a Kinect v2 it does not contribute detections. When the Kinect v2 is not detecting there is not indication of an issue in the terminal window running the detection process.

We have also noticed the same issue, but after the Kinect v2 has been detecting properly for some time. It will stop detecting after functioning properly, but give no indication in the terminal window running the detection.

**Comment by nanodust** [comment] 2015-10-06 20:06
is this still an issue ? 

I've had my OPT Kinect 2 system up for over 3 weeks, and it still detects fine. 

(note I have not done full (intrinsic, extrinsic) calibration... but it has been working fine without)

**Comment by mmunaro** [comment] 2015-10-07 07:57
From my side, I was not able to reproduce this issue, thus I was not sure how to debug it.

**Comment by randydevitt** [comment] 2016-06-23 14:34
Just began having this problem yesterday, @lthursdayl did you find any explanation for why it stopped detecting?

**Comment by nanodust** [comment] 2016-06-23 16:27
on my (single camera, single CPU) dev system - I've run detection w/ Kinect 2 for at least a few weeks, likely longer, and it's continued to detect, as expected, no problems. 

I suspect the only way to actually debug this is to post complete log files for the offending session.

**Comment by randydevitt** [comment] 2016-06-24 16:02
We've been looking more into it, and it appears to be a hardwdare issue
specifically with that laptop. The laptop is an hp elitebook with a WD 8tb
usb hard drive hooked up. While recording bag files from the computer the
kinect will periodically stop functioning with no indication. This happens
when recording both the trackers_array_smoothed and camera feeds. It
doesn't seem to be a cpu overload, however when the kinect stops
functioning the cpu usage drops significantly


*Randall Devitt*
Stevens Institute of Technology '19
Mechanical Engineering
862-812-7247

**Comment by randydevitt** [comment] 2016-06-24 16:18
another thing we saw is "working buffer full, resetting it"

*Randall Devitt*
Stevens Institute of Technology '19
Mechanical Engineering
862-812-7247

**Comment by jburkeucla** [comment] 2017-07-03 20:36
Looks like USB3 issue; abandoned?  Closing.

**Closed by jburkeucla** 2017-07-03 20:36 UTC
Labels: bug
